In [16]:
import pandas as pd
report = '/home/quanpn3/Documents/My_project/UI-Voyager/eval_results/UI-Voyager/logs/20260403105821/detailed_results.csv'
df = pd.read_csv(report)

In [17]:
df.head(10)

,task_template,num_complete_trials,mean_success_rate,mean_episode_length,total_runtime_s,num_fail_trials,difficulty,optimal_steps,tags
0,AudioRecorderRecordAudio,0,NaN,NaN,0.6,1,easy,6,['requires_setup']
1,AudioRecorderRecordAudioWithFileName,1,0.0,20.0,115.2,0,easy,10,"['data_entry', 'complex_ui_understanding', 'pa..."
2,BrowserDraw,1,0.0,20.0,94.3,0,easy,5,"['game_playing', 'parameterized']"
3,BrowserMaze,1,0.0,20.0,91.5,0,easy,9,"['game_playing', 'multi_app', 'complex_ui_unde..."
4,BrowserMultiply,1,0.0,22.0,101.9,0,hard,11,"['math_counting', 'memorization', 'screen_read..."
5,CameraTakePhoto,1,0.0,10.0,52.1,0,easy,2,['']
6,CameraTakeVideo,1,0.0,10.0,56.3,0,medium,3,['']
7,ClockStopWatchPausedVerify,1,1.0,6.0,29.8,0,easy,1,['verification']
8,ClockStopWatchRunning,1,1.0,3.0,19.5,0,easy,3,['']
9,ClockTimerEntry,1,1.0,9.0,47.1,0,easy,3,"['data_entry', 'parameterized']"

In [25]:
!ls eval_results/UI-Voyager/logs/20260403105821/detailed_results.csv

eval_results/UI-Voyager/logs/20260403105821/detailed_results.csv

In [40]:
df.head(50)

,task_template,num_complete_trials,mean_success_rate,mean_episode_length,total_runtime_s,num_fail_trials,difficulty,optimal_steps,tags
0,AudioRecorderRecordAudio,0,NaN,NaN,0.6,1,easy,6,['requires_setup']
1,AudioRecorderRecordAudioWithFileName,1,0.0,20.0,115.2,0,easy,10,"['data_entry', 'complex_ui_understanding', 'pa..."
2,BrowserDraw,1,0.0,20.0,94.3,0,easy,5,"['game_playing', 'parameterized']"
3,BrowserMaze,1,0.0,20.0,91.5,0,easy,9,"['game_playing', 'multi_app', 'complex_ui_unde..."
4,BrowserMultiply,1,0.0,22.0,101.9,0,hard,11,"['math_counting', 'memorization', 'screen_read..."
5,CameraTakePhoto,1,0.0,10.0,52.1,0,easy,2,['']
6,CameraTakeVideo,1,0.0,10.0,56.3,0,medium,3,['']
7,ClockStopWatchPausedVerify,1,1.0,6.0,29.8,0,easy,1,['verification']
8,ClockStopWatchRunning,1,1.0,3.0,19.5,0,easy,3,['']
9,ClockTimerEntry,1,1.0,9.0,47.1,0,easy,3,"['data_entry', 'parameterized']"
10,ContactsAddContact,1,1.0,11.0,57.7,0,easy,5,"['data_entry', 'parameterized']"
11,ContactsNewContactDraft,1,0.0,12.0,57.9,0,easy,6,"['screen_reading', 'data_entry']"
12,ExpenseAddMultiple,0,NaN,NaN,0.8,1,medium,20,"['data_entry', 'parameterized']"
13,ExpenseAddMultipleFromGallery,0,NaN,NaN,0.6,1,hard,10,"['multi_app', 'screen_reading', 'data_entry', ..."
14,ExpenseAddMultipleFromMarkor,0,NaN,NaN,0.3,1,hard,15,"['transcription', 'repetition', 'multi_app', '..."
15,ExpenseAddSingle,0,NaN,NaN,0.3,1,easy,6,"['parameterized', 'data_entry', 'search']"
16,ExpenseDeleteDuplicates,0,NaN,NaN,0.3,1,medium,6,"['data_edit', 'parameterized']"
17,ExpenseDeleteDuplicates2,0,NaN,NaN,0.3,1,medium,9,"['data_edit', 'requires_setup', 'parameterized']"
18,ExpenseDeleteMultiple,0,NaN,NaN,0.3,1,easy,10,"['data_edit', 'parameterized']"
19,ExpenseDeleteMultiple2,0,NaN,NaN,2.3,1,hard,17,"['screen_reading', 'parameterized']"
20,ExpenseDeleteSingle,0,NaN,NaN,2.2,1,easy,3,"['screen_reading', 'parameterized']"
21,FilesDeleteFile,1,0.0,8.0,39.7,0,medium,4,"['data_edit', 'parameterized']"
22,FilesMoveFile,1,0.0,15.0,75.2,0,medium,10,"['search', 'screen_reading', 'parameterized']"
23,MarkorAddNoteHeader,1,0.0,12.0,68.7,0,medium,6,"['data_entry', 'parameterized']"
24,MarkorChangeNoteContent,1,0.0,12.0,65.7,0,medium,5,"['data_entry', 'requires_setup', 'parameterized']"
25,MarkorCreateFolder,1,0.0,10.0,55.8,0,easy,4,"['data_entry', 'parameterized']"
26,MarkorCreateNote,1,0.0,16.0,91.3,0,medium,8,"['data_entry', 'parameterized']"
27,MarkorCreateNoteAndSms,1,0.0,18.0,111.5,0,hard,9,"['multi_app', 'data_entry', 'parameterized']"
28,MarkorCreateNoteFromClipboard,0,NaN,NaN,3.8,1,medium,7,"['data_entry', 'parameterized']"
29,MarkorDeleteAllNotes,1,0.0,14.0,73.9,0,easy,7,"['data_edit', 'repetition', 'parameterized']"
30,MarkorDeleteNewestNote,1,0.0,10.0,56.1,0,easy,4,"['data_edit', 'parameterized']"
31,MarkorDeleteNote,1,0.0,10.0,56.8,0,easy,5,"['data_edit', 'requires_setup', 'parameterized']"
32,MarkorEditNote,1,0.0,12.0,67.7,0,easy,4,"['data_edit', 'transcription', 'parameterized']"
33,MarkorMergeNotes,1,0.0,78.0,414.5,0,hard,39,"['data_edit', 'data_entry', 'parameterized']"
34,MarkorMoveNote,1,0.0,14.0,79.6,0,medium,7,"['parameterized', 'complex_ui_understanding']"
35,MarkorTranscribeReceipt,1,0.0,18.0,99.6,0,medium,9,"['transcription', 'data_entry', 'multi_app', '..."
36,MarkorTranscribeVideo,1,0.0,20.0,111.4,0,hard,10,"['multi_app', 'transcription', 'requires_setup..."
37,NotesIsTodo,0,NaN,NaN,9.6,1,easy,2,"['information_retrieval', 'parameterized']"
38,NotesMeetingAttendeeCount,0,NaN,NaN,9.4,1,easy,3,"['search', 'parameterized']"
39,NotesRecipeIngredientCount,0,NaN,NaN,7.4,1,easy,2,"['search', 'parameterized']"
40,NotesTodoItemCount,0,NaN,NaN,7.4,1,medium,5,"['information_retrieval', 'math_counting', 'pa..."
41,OpenAppTaskEval,1,1.0,3.0,15.5,0,easy,2,['parameterized']
42,OsmAndFavorite,1,0.0,13.0,75.8,0,medium,6,"['search', 'complex_ui_understanding', 'parame..."
43,OsmAndMarker,0,NaN,NaN,9.3,1,hard,10,"['complex_ui_understanding', 'search', 'parame..."
44,OsmAndTrack,0,NaN,NaN,624.2,1,hard,60,"['complex_ui_understanding', 'search', 'data_e..."
45,RecipeAddMultipleRecipes,0,NaN,NaN,9.4,1,medium,34,"['data_entry', 'parameterized']"
46,RecipeAddMultipleRecipesFromImage,0,NaN,NaN,9.2,1,hard,13,"['transcription', 'screen_reading', 'data_entr..."
47,RecipeAddMultipleRecipesFromMarkor,0,NaN,NaN,9.2,1,hard,24,"['data_entry', 'multi_app', 'screen_reading', ..."
48,RecipeAddMultipleRecipesFromMarkor2,0,NaN,NaN,7.2,1,hard,26,"['parameterized', 'screen_reading', 'complex_u..."
49,RecipeAddSingleRecipe,0,NaN,NaN,7.2,1,easy,12,"['data_entry', 'parameterized']"

In [45]:
df.iloc[50:100,]

,task_template,num_complete_trials,mean_success_rate,mean_episode_length,total_runtime_s,num_fail_trials,difficulty,optimal_steps,tags
50,RecipeDeleteDuplicateRecipes,0,NaN,NaN,7.2,1,easy,4,"['search', 'data_edit', 'screen_reading', 'rep..."
51,RecipeDeleteDuplicateRecipes2,0,NaN,NaN,9.3,1,medium,11,"['repetition', 'data_edit', 'parameterized']"
52,RecipeDeleteDuplicateRecipes3,0,NaN,NaN,7.2,1,medium,16,"['data_edit', 'parameterized']"
53,RecipeDeleteMultipleRecipes,0,NaN,NaN,7.2,1,easy,12,"['data_edit', 'parameterized']"
54,RecipeDeleteMultipleRecipesWithConstraint,0,NaN,NaN,9.2,1,hard,20,"['screen_reading', 'repetition', 'parameterized']"
55,RecipeDeleteMultipleRecipesWithNoise,0,NaN,NaN,7.2,1,medium,17,"['parameterized', 'search', 'complex_ui_unders..."
56,RecipeDeleteSingleRecipe,0,NaN,NaN,9.2,1,easy,5,"['data_edit', 'search', 'parameterized']"
57,RecipeDeleteSingleWithRecipeWithNoise,0,NaN,NaN,7.2,1,easy,10,"['search', 'screen_reading', 'data_edit', 'par..."
58,RetroCreatePlaylist,0,NaN,NaN,9.4,1,medium,12,"['data_entry', 'repetition', 'parameterized']"
59,RetroPlayingQueue,0,NaN,NaN,9.4,1,easy,16,['parameterized']
60,RetroPlaylistDuration,0,NaN,NaN,7.2,1,medium,15,"['math_counting', 'complex_ui_understanding', ..."
61,RetroSavePlaylist,0,NaN,NaN,7.5,1,hard,25,"['search', 'repetition', 'parameterized']"
62,SaveCopyOfReceiptTaskEval,1,0.0,16.0,85.7,0,hard,8,"['parameterized', 'complex_ui_understanding']"
63,SimpleCalendarAddOneEvent,0,NaN,NaN,9.5,1,hard,17,"['data_entry', 'complex_ui_understanding', 'pa..."
64,SimpleCalendarAddOneEventInTwoWeeks,0,NaN,NaN,9.3,1,medium,10,"['data_entry', 'math_counting', 'parameterized']"
65,SimpleCalendarAddOneEventRelativeDay,0,NaN,NaN,7.2,1,easy,17,"['data_entry', 'parameterized']"
66,SimpleCalendarAddOneEventTomorrow,0,NaN,NaN,7.2,1,easy,13,"['data_entry', 'parameterized']"
67,SimpleCalendarAddRepeatingEvent,0,NaN,NaN,7.3,1,easy,14,"['data_entry', 'complex_ui_understanding', 'pa..."
68,SimpleCalendarAnyEventsOnDate,0,NaN,NaN,9.5,1,easy,4,"['information_retrieval', 'parameterized']"
69,SimpleCalendarDeleteEvents,0,NaN,NaN,7.2,1,easy,7,"['parameterized', 'data_edit']"
70,SimpleCalendarDeleteEventsOnRelativeDay,0,NaN,NaN,7.2,1,medium,6,"['data_edit', 'parameterized']"
71,SimpleCalendarDeleteOneEvent,0,NaN,NaN,9.2,1,easy,6,"['data_edit', 'complex_ui_understanding', 'par..."
72,SimpleCalendarEventOnDateAtTime,0,NaN,NaN,7.4,1,medium,3,"['information_retrieval', 'parameterized']"
73,SimpleCalendarEventsInNextWeek,0,NaN,NaN,9.5,1,easy,3,"['data_entry', 'parameterized']"
74,SimpleCalendarEventsInTimeRange,0,NaN,NaN,9.4,1,easy,2,"['complex_ui_understanding', 'screen_reading',..."
75,SimpleCalendarEventsOnDate,0,NaN,NaN,7.5,1,medium,4,"['information_retrieval', 'parameterized']"
76,SimpleCalendarFirstEventAfterStartTime,0,NaN,NaN,7.5,1,easy,2,"['parameterized', 'screen_reading']"
77,SimpleCalendarLocationOfEvent,0,NaN,NaN,7.4,1,easy,4,"['search', 'parameterized']"
78,SimpleCalendarNextEvent,0,NaN,NaN,7.6,1,easy,4,"['complex_ui_understanding', 'screen_reading',..."
79,SimpleCalendarNextMeetingWithPerson,0,NaN,NaN,7.5,1,medium,5,"['information_retrieval', 'parameterized']"
80,SimpleDrawProCreateDrawing,1,0.0,18.0,93.0,0,easy,9,"['data_entry', 'parameterized']"
81,SimpleSmsReply,0,NaN,NaN,44.2,1,easy,4,"['search', 'data_entry', 'parameterized']"
82,SimpleSmsReplyMostRecent,0,NaN,NaN,41.5,1,medium,5,['parameterized']
83,SimpleSmsResend,0,NaN,NaN,62.6,1,medium,6,['parameterized']
84,SimpleSmsSend,1,0.0,12.0,78.1,0,medium,6,['parameterized']
85,SimpleSmsSendClipboardContent,0,NaN,NaN,9.6,1,easy,6,"['data_entry', 'parameterized']"
86,SimpleSmsSendReceivedAddress,0,NaN,NaN,59.0,1,medium,9,"['information_retrieval', 'parameterized']"
87,SportsTrackerActivitiesCountForWeek,0,NaN,NaN,7.5,1,easy,3,"['search', 'requires_setup', 'parameterized']"
88,SportsTrackerActivitiesOnDate,0,NaN,NaN,9.4,1,hard,10,"['search', 'complex_ui_understanding', 'screen..."
89,SportsTrackerActivityDuration,0,NaN,NaN,7.5,1,easy,6,"['information_retrieval', 'parameterized']"
90,SportsTrackerLongestDistanceActivity,0,NaN,NaN,7.5,1,easy,2,"['parameterized', 'screen_reading', 'informati..."
91,SportsTrackerTotalDistanceForCategoryOverInterval,0,NaN,NaN,7.5,1,hard,11,"['search', 'parameterized', 'math_counting']"
92,SportsTrackerTotalDurationForCategoryThisWeek,0,NaN,NaN,7.4,1,hard,8,"['math_counting', 'search', 'parameterized']"
93,SystemBluetoothTurnOff,1,1.0,5.0,22.1,0,easy,2,['']
94,SystemBluetoothTurnOffVerify,1,1.0,6.0,29.2,0,easy,2,['verification']
95,SystemBluetoothTurnOn,1,1.0,5.0,24.8,0,easy,2,['screen_reading']
96,SystemBluetoothTurnOnVerify,1,1.0,6.0,29.1,0,easy,2,['verification']
97,SystemBrightnessMax,1,1.0,7.0,37.3,0,easy,3,['']
98,SystemBrightnessMaxVerify,1,1.0,5.0,29.4,0,easy,2,['verification']
99,SystemBrightnessMin,1,0.0,8.0,37.5,0,easy,3,['']

In [44]:
df.iloc[100:116, :]

,task_template,num_complete_trials,mean_success_rate,mean_episode_length,total_runtime_s,num_fail_trials,difficulty,optimal_steps,tags
100,SystemBrightnessMinVerify,1,1.0,6.0,29.4,0,easy,3,['verification']
101,SystemCopyToClipboard,0,NaN,NaN,3.4,1,easy,2,"['data_entry', 'parameterized']"
102,SystemWifiTurnOff,1,1.0,4.0,21.5,0,easy,3,['screen_reading']
103,SystemWifiTurnOffVerify,1,1.0,4.0,21.5,0,easy,3,['verification']
104,SystemWifiTurnOn,1,1.0,4.0,23.8,0,easy,3,['screen_reading']
105,SystemWifiTurnOnVerify,1,1.0,3.0,17.7,0,easy,3,['verification']
106,TasksCompletedTasksForDate,0,NaN,NaN,9.8,1,medium,5,"['information_retrieval', 'search', 'parameter..."
107,TasksDueNextWeek,0,NaN,NaN,7.5,1,medium,6,"['information_retrieval', 'parameterized']"
108,TasksDueOnDate,0,NaN,NaN,7.4,1,easy,2,"['search', 'parameterized']"
109,TasksHighPriorityTasks,0,NaN,NaN,7.4,1,medium,2,"['complex_ui_understanding', 'search', 'inform..."
110,TasksHighPriorityTasksDueOnDate,0,NaN,NaN,7.5,1,medium,5,"['information_retrieval', 'screen_reading', 'p..."
111,TasksIncompleteTasksOnDate,0,NaN,NaN,9.4,1,easy,2,"['parameterized', 'screen_reading', 'informati..."
112,TurnOffWifiAndTurnOnBluetooth,1,1.0,6.0,29.7,0,medium,5,['']
113,TurnOnWifiAndOpenApp,1,0.0,20.0,109.0,0,easy,4,['parameterized']
114,VlcCreatePlaylist,0,NaN,NaN,25.7,1,medium,14,"['data_edit', 'repetition', 'parameterized']"
115,VlcCreateTwoPlaylists,0,NaN,NaN,25.6,1,medium,24,"['data_entry', 'requires_setup', 'parameterized']"